name: nobet_matik_3
description: "otomatik liste programı"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter # Bu satırı ekledim
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.0
  syncfusion_flutter_datepicker: ^24.1.45
  intl: ^0.18.0
  cupertino_icons: ^1.0.6 # Eğer bu bağımlılığı kullanıyorsanız ekleyin

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo.jpg
    - assets/icons/gun_ayari.png
    - assets/icons/liste_tarihi_sec.png
    - assets/icons/personeller.png
